name: CI


on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python3@v2
      with:
        python3-version: 3.7
    - name: Cache PyPI
      uses: actions/cache@v2
      with:
        key: pip-cache-lint-${{ hashFiles('requirements-dev.txt') }}
        path: ~/.cache/pip
        restore-keys: |
            pip-cache-lint
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: requirements-dev.txt
    - name: Run linters
      run: |
        make lint
  test:
    strategy:
      matrix:
        python3-version: ['3.6', '3.7', '3.8']
      fail-fast: true
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Prepare Environment
        run: |
          sudo apt install -q -y curl software-properties-common build-essential
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-add-repository https://packages.microsoft.com/ubuntu/18.04/prod
          env DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y sudo -E apt install -q -y  libk4a1.4-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python  ${{ matrix.python3-version }}
        uses: actions/setup-python3@v2
        with:
          python3-version:  ${{ matrix.python3-version }}
      - name: Cache PyPI
        uses: actions/cache@v2
        with:
          key: pip-cache-test-${{ matrix.python3-version }}-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('setup.py') }}
          path: ~/.cache/pip
          restore-keys: |
              pip-cache-test-${{ matrix.python3-version }}
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: requirements-dev.txt
      - name: Install module
        run:
          pip3 install -e .
      - name: Run tests
        run: |
          make test-no-hardware
      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml # optional
